// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "945babab-a18f-4158-b8f5-db157b872a76";

// To avoid having a 'secret' file, pass the IDs and Keys as the constants they are


const char SSID[]               = "INFINITUMF9F8_2.4";    // Network SSID (name)
const char PASS[]               = "4128055401";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "A2Z6FYPVLCQWUVLVFSHC";    // Secret device password

// const char SSID[]               = SECRET_SSID;    // Network SSID (name)
// const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
// const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


String exploreStatus;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(exploreStatus, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
